import { ProjectType } from "./columns";

export const projects: ProjectType[] = [
  {
    id: "PRJ-0101",
    cliente: "Edifício Solaris",
    country: "Brasil",
    deadline: "2025-11-15",
    status: "Active",
    assignee: "Ana Silva",
    actions: "Ver",
  },
  {
    id: "PRJ-0102",
    cliente: "Torres Altas",
    country: "Argentina",
    deadline: "2025-12-01",
    status: "Production",
    assignee: "Carlos Pereira",
    actions: "Ver",
  },
  {
    id: "PRJ-0103",
    cliente: "Condomínio Central",
    country: "Chile",
    deadline: "2025-10-20",
    status: "Done",
    assignee: "Maria Oliveira",
    actions: "Ver",
  },
  {
    id: "PRJ-0104",
    cliente: "Cliente Feliz S.A.",
    country: "Colômbia",
    deadline: "2026-01-10",
    status: "Production",
    assignee: "João Santos",
    actions: "Ver",
  },
  {
    id: "PRJ-0105",
    cliente: "Edifícios Seguros",
    country: "México",
    deadline: "2025-11-25",
    status: "Active",
    assignee: "Sofia Costa",
    actions: "Ver",
  },
  {
    id: "PRJ-0106",
    cliente: "Horizonte Vertical",
    country: "Peru",
    deadline: "2026-02-01",
    status: "Sale",
    assignee: "Miguel Rodrigues",
    actions: "Ver",
  },
  {
    id: "PRJ-0107",
    cliente: "Pátio das Nações",
    country: "Brasil",
    deadline: "2025-11-05",
    status: "Paused",
    assignee: "Laura Fernandes",
    actions: "Ver",
  },
  {
    id: "PRJ-0108",
    cliente: "Centro Empresarial",
    country: "Argentina",
    deadline: "2025-09-30",
    status: "Done",
    assignee: "Bruno Almeida",
    actions: "Ver",
  },
  {
    id: "PRJ-0109",
    cliente: "Residencial Harmonia",
    country: "Brasil",
    deadline: "2026-01-20",
    status: "Production",
    assignee: "Ana Silva",
    actions: "Ver",
  },
  {
    id: "PRJ-0110",
    cliente: "Comercial Américas",
    country: "Chile",
    deadline: "2025-12-15",
    status: "Active",
    assignee: "Carlos Pereira",
    actions: "Ver",
  },
  {
    id: "PRJ-0111",
    cliente: "Plaza Mayor",
    country: "México",
    deadline: "2025-11-18",
    status: "Paused",
    assignee: "Maria Oliveira",
    actions: "Ver",
  },
  {
    id: "PRJ-0112",
    cliente: "Edifício Innovations",
    country: "Colômbia",
    deadline: "2025-10-10",
    status: "Done",
    assignee: "João Santos",
    actions: "Ver",
  },
  {
    id: "PRJ-0113",
    cliente: "Torre del Sol",
    country: "Peru",
    deadline: "2026-03-01",
    status: "Sale",
    assignee: "Sofia Costa",
    actions: "Ver",
  },
  {
    id: "PRJ-0114",
    cliente: "Residencial Pacífico",
    country: "Chile",
    deadline: "2026-02-14",
    status: "Production",
    assignee: "Miguel Rodrigues",
    actions: "Ver",
  },
  {
    id: "PRJ-0115",
    cliente: "Business Tower",
    country: "Brasil",
    deadline: "2025-12-20",
    status: "Active",
    assignee: "Laura Fernandes",
    actions: "Ver",
  },
  {
    id: "PRJ-0116",
    cliente: "Condomínio Atlântico",
    country: "Uruguai",
    deadline: "2025-11-30",
    status: "Production",
    assignee: "Bruno Almeida",
    actions: "Ver",
  },
  {
    id: "PRJ-0117",
    cliente: "Vista Hermosa",
    country: "Argentina",
    deadline: "2025-11-12",
    status: "Paused",
    assignee: "Ana Silva",
    actions: "Ver",
  },
  {
    id: "PRJ-0118",
    cliente: "Centro Logístico",
    country: "Brasil",
    deadline: "2025-10-01",
    status: "Done",
    assignee: "Carlos Pereira",
    actions: "Ver",
  },
  {
    id: "PRJ-0119",
    cliente: "Parque Industrial",
    country: "México",
    deadline: "2026-01-30",
    status: "Production",
    assignee: "Maria Oliveira",
    actions: "Ver",
  },
  {
    id: "PRJ-0120",
    cliente: "Edifício Corporativo",
    country: "Colômbia",
    deadline: "2025-12-05",
    status: "Active",
    assignee: "João Santos",
    actions: "Ver",
  },
  {
    id: "PRJ-0121",
    cliente: "Residencial das Flores",
    country: "Brasil",
    deadline: "2026-02-20",
    status: "Sale",
    assignee: "Sofia Costa",
    actions: "Ver",
  },
  {
    id: "PRJ-0122",
    cliente: "Torre de Buenos Aires",
    country: "Argentina",
    deadline: "2025-11-22",
    status: "Active",
    assignee: "Miguel Rodrigues",
    actions: "Ver",
  },
  {
    id: "PRJ-0123",
    cliente: "Santiago Business",
    country: "Chile",
    deadline: "2025-10-25",
    status: "Paused",
    assignee: "Laura Fernandes",
    actions: "Ver",
  },
  {
    id: "PRJ-0124",
    cliente: "Lima Financial",
    country: "Peru",
    deadline: "2025-10-15",
    status: "Done",
    assignee: "Bruno Almeida",
    actions: "Ver",
  },
  {
    id: "PRJ-0125",
    cliente: "Condomínio Imperial",
    country: "Brasil",
    deadline: "2026-01-05",
    status: "Production",
    assignee: "Ana Silva",
    actions: "Ver",
  },
  {
    id: "PRJ-0126",
    cliente: "Montevideo Plaza",
    country: "Uruguai",
    deadline: "2025-12-28",
    status: "Active",
    assignee: "Carlos Pereira",
    actions: "Ver",
  },
  {
    id: "PRJ-0127",
    cliente: "Bogotá Tower",
    country: "Colômbia",
    deadline: "2025-11-10",
    status: "Paused",
    assignee: "Maria Oliveira",
    actions: "Ver",
  },
  {
    id: "PRJ-0128",
    cliente: "Cancun Resorts",
    country: "México",
    deadline: "2025-10-30",
    status: "Done",
    assignee: "João Santos",
    actions: "Ver",
  },
  {
    id: "PRJ-0129",
    cliente: "Edifício Pátria",
    country: "Brasil",
    deadline: "2026-03-10",
    status: "Sale",
    assignee: "Sofia Costa",
    actions: "Ver",
  },
  {
    id: "PRJ-0130",
    cliente: "Porto Madero",
    country: "Argentina",
    deadline: "2026-02-05",
    status: "Production",
    assignee: "Miguel Rodrigues",
    actions: "Ver",
  },
];
